[theme]
primaryColor = "#C5A880"
backgroundColor = "#081426"
secondaryBackgroundColor = "#0F243E"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
